### ISSUE TITLE
gulp uat crashes

### ISSUE THREAD

**Issue by KarlTheCool** [GenderDysphoria/GenderDysphoria.fyi#132]
Happens also if you build for dev too.

[Full log.txt](https://github.com/GenderDysphoria/GenderDysphoria.fyi/files/11493639/log.txt)

```
[02:31:54] TypeError: Error while processing page "public/zh/printable.md": Cannot read properties of undefined (reading 'type')
    at Array.<anonymous> (/workspace/GenderDysphoria.fyi/build/lib/markdown-raw-html.js:83:43)
    at ParserBlock.tokenize (/workspace/GenderDysphoria.fyi/node_modules/markdown-it/lib/parser_block.js:79:20)
    at ParserBlock.parse (/workspace/GenderDysphoria.fyi/node_modules/markdown-it/lib/parser_block.js:115:8)
    at Array.block (/workspace/GenderDysphoria.fyi/node_modules/markdown-it/lib/rules_core/block.js:14:20)
    at Core.process (/workspace/GenderDysphoria.fyi/node_modules/markdown-it/lib/parser_core.js:54:13)
    at MarkdownIt.parse (/workspace/GenderDysphoria.fyi/node_modules/markdown-it/lib/index.js:524:13)
    at MarkdownIt.render (/workspace/GenderDysphoria.fyi/node_modules/markdown-it/lib/index.js:544:36)
    at markdown (/workspace/GenderDysphoria.fyi/build/engines.js:84:42)
    at Object.ENGINE_PAGE (/workspace/GenderDysphoria.fyi/build/engines.js:145:78)
    at /workspace/GenderDysphoria.fyi/build/page-writer.js:128:45
    at bound (node:domain:433:15)
    at runBound (node:domain:444:12)
From previous event:
    at processImmediate (node:internal/timers:466:21)
    at process.topLevelDomainCallback (node:domain:161:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
From previous event:
    at processPages (/workspace/GenderDysphoria.fyi/build/page-writer.js:122:18)
    at writePageContent (/workspace/GenderDysphoria.fyi/build/page-writer.js:20:9)
    at fn (/workspace/GenderDysphoria.fyi/build/index.js:87:29)
[02:31:54] 'uat' errored after 24 s
```

**Comment by Twipped** [comment]
Fixed, there was some bad markdown in one of the chinese translation files
